// Generated by CoffeeScript 1.6.2
(function() {
  var between;

  between = function(paragraph, start, end) {
    var endIndex, startIndex;

    startIndex = paragraph.indexOf(start);
    endIndex = paragraph.indexOf(end, startIndex);
    return paragraph.slice(startIndex + start.length, endIndex);
  };

  show(between('born 15/11/2003 (mother Spot): White Fang', '(mother ', ')'));

}).call(this);
