// Generated by CoffeeScript 1.6.2
(function() {
  var catNames;

  catNames = function(paragraph) {
    var colon;

    colon = paragraph.indexOf(':');
    return paragraph.slice(colon + 2).split(', ');
  };

  show(catNames('born 20/09/2004 (mother Yello Bess): ' + 'Doctor Hobbles the 2nd, Noog'));

}).call(this);
