// Generated by CoffeeScript 1.6.2
(function() {
  var date, formatDate;

  formatDate = function(date) {
    var day, month, year;

    day = date.getDate();
    month = date.getMonth() + 1;
    year = date.getFullYear();
    if (day < 10) {
      day = "0" + day;
    }
    if (month < 10) {
      month = "0" + month;
    }
    return "" + day + "/" + month + "/" + year;
  };

  date = new Date;

  show(formatDate(date));

}).call(this);
