// Generated by CoffeeScript 1.6.2
(function() {
  var counter, multiply_by_two, string, value, _i, _j;

  multiply_by_two = function(number) {
    return number * 2;
  };

  value = 1;

  for (counter = _i = 1; _i <= 10; counter = ++_i) {
    print(value = multiply_by_two(value));
  }

  string = '';

  for (counter = _j = 1; _j <= 10; counter = ++_j) {
    string += '#';
    print(string);
  }

}).call(this);
