// Generated by CoffeeScript 1.6.2
(function() {
  var counter, string;

  counter = 0;

  string = '';

  while (counter <= 10) {
    string += '#';
    show(string);
    counter += 1;
  }

}).call(this);
