// Generated by CoffeeScript 1.6.2
(function() {
  prompt('Please pick a number between 1 to 6: ', '', function(lucky_number) {
    var number_of_rolls, roll, _results;

    lucky_number = parseInt(lucky_number);
    number_of_rolls = 0;
    _results = [];
    while (true) {
      number_of_rolls += 1;
      roll = Math.floor(Math.random() * 6 + 1);
      if (roll === lucky_number) {
        show("It took " + number_of_rolls + " to get your lucky number " + lucky_number + ".");
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });

}).call(this);
