// Generated by CoffeeScript 1.6.2
(function() {
  var fn, greaterThan;

  greaterThan = function(number) {
    return function(x) {
      return x > number;
    };
  };

  fn = greaterThan(5);

  show(fn(4));

  show(fn(5));

  show(fn(6));

}).call(this);
