// Generated by CoffeeScript 1.6.2
(function() {
  var ageOfCat, oldestCat;

  ageOfCat = function(cat) {
    return cat.death - cat.birth;
  };

  oldestCat = function(cats) {
    var age, cat, name, oldest;

    oldest = null;
    for (name in cats) {
      cat = cats[name];
      age = ageOfCat(cat);
      if (oldest === null || ageOfCat(oldest) < ageOfCat(cat)) {
        oldest = cat;
      }
    }
    return oldest != null ? oldest.name : void 0;
  };

  show(oldestCat(catData));

}).call(this);
