// Generated by CoffeeScript 1.6.2
(function() {
  var counter, multiply_by_two, value;

  multiply_by_two = function(number) {
    return number * 2;
  };

  counter = 0;

  value = 1;

  while (counter <= 10) {
    show(value = multiply_by_two(value));
    counter += 1;
  }

}).call(this);
