// Generated by CoffeeScript 1.6.2
(function() {
  var makeRoads;

  makeRoads = function(start) {
    var even, i, _i, _ref, _results;

    even = function(num) {
      return num % 2 === 0;
    };
    if (even(arguments.length) || arguments.length < 3) {
      throw new Error("Wrong number of args for makeRoads (" + arguments.length + " of " + (Math.max(3, arguments.length + 1)) + ")");
    }
    _results = [];
    for (i = _i = 1, _ref = arguments.length; _i < _ref; i = _i += 2) {
      _results.push(makeRoad(start, arguments[i], arguments[i + 1]));
    }
    return _results;
  };

  makeRoads('Happy Valley', 'Central', 15, 'Wan Chai', 16);

  show(roads);

}).call(this);
