// Generated by CoffeeScript 1.6.2
(function() {
  var absolute;

  absolute = function(x) {
    if (x < 0) {
      return x * -1;
    } else {
      return x;
    }
  };

  print(absolute(2));

  print(absolute(-3.0));

  print(absolute(-0));

}).call(this);
