// Generated by CoffeeScript 1.6.2
(function() {
  var startsWith;

  startsWith = function(string, chars) {
    if (string.slice(0, chars.length) === chars) {
      return true;
    } else {
      return false;
    }
  };

  show(startsWith('Write a function called', 'Write'));

  show(startsWith('Write a function called', 'called'));

  show(startsWith('called', 'Write a function called'));

  show(startsWith('Write', 'Write a function called'));

}).call(this);
