// Generated by CoffeeScript 1.6.2
(function() {
  var sum;

  sum = function(range) {
    var num, total, _i, _len;

    total = 0;
    for (_i = 0, _len = range.length; _i < _len; _i++) {
      num = range[_i];
      total += num;
    }
    return total;
  };

  show(sum([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]));

  show(sum(range(1, 10)));

}).call(this);
