// Generated by CoffeeScript 1.6.2
(function() {
  var renderFragment, renderParagraph;

  renderFragment = function(fragment) {
    if (fragment.type === 'reference') {
      return footnote(fragment.number);
    } else if (fragment.type === 'emphasised') {
      return tag('em', [fragment.content]);
    } else if (fragment.type === 'normal') {
      return fragment.content;
    }
  };

  renderParagraph = function(paragraph) {
    return tag(paragraph.type, map(paragraph.content, renderFragment));
  };

  show(renderParagraph(paragraphs[2]));

}).call(this);
