// Generated by CoffeeScript 1.6.2
(function() {
  var a, count, countZeroes, countZeros, equals;

  a = [1, 2, 3, 4, 5, 6, 7, 8, 0, 0];

  countZeroes = function(array) {
    var counter;

    counter = function(total, element) {
      if (element === 0) {
        total++;
      }
      return total;
    };
    return reduce(array, counter, 0);
  };

  show(countZeroes(a));

  count = function(test, array) {
    return reduce(array, (function(total, element) {
      return total + (test(element) ? 1 : 0);
    }), 0);
  };

  equals = function(x) {
    return function(element) {
      return x === element;
    };
  };

  countZeros = function(array) {
    return count(equals(0), array);
  };

  show(countZeroes(a));

}).call(this);
