// Generated by CoffeeScript 1.6.2
(function() {
  var extractDate, paragraph;

  paragraph = 'died 27/04/2006: Black Leclère';

  extractDate = function(paragraph) {
    var day, month, year;

    day = Number(paragraph.slice(5, 7));
    month = Number(paragraph.slice(8, 10) - 1);
    year = Number(paragraph.slice(11, 15));
    return new Date(year, month, day);
  };

  show(extractDate(paragraph));

}).call(this);
