// Generated by CoffeeScript 1.6.2
(function() {
  prompt("What's 2 + 2?", '', function(answer) {
    if (answer === '4') {
      return show("Great! You know how to add basic numbers!");
    } else if (answer === '3' || answer === '5') {
      return show("Almost, but no cigar!");
    } else {
      return show("You're pretty dumb.");
    }
  });

}).call(this);
