// Generated by CoffeeScript 1.6.2
(function() {
  var p, splitParagraph;

  p = "Realising this problem, the programmer will start to spenda lot of time thinking about *structure.* His programs willbe rigidly structured, like rock sculptures. They are solid,but when they must change, violence must be done to them{Referring to the fact that structure tends to putrestrictions on the evolution of a program.}.";

  splitParagraph = function(text) {
    var content, fragments, indexOrEnd, nextIndexOrEnd, takeNormal, takeUpTo, upToIndex;

    indexOrEnd = function(char) {
      var index;

      index = text.indexOf(char);
      if (index === -1) {
        return text.length;
      } else {
        return index;
      }
    };
    nextIndexOrEnd = function() {
      return Math.min.apply(Math, ['*', '{'].map(indexOrEnd));
    };
    upToIndex = function(index) {
      var content;

      content = text.slice(0, index);
      text = text.slice(index);
      return content;
    };
    takeNormal = function() {
      return upToIndex(nextIndexOrEnd());
    };
    takeUpTo = function(char) {
      var content;

      text = text.slice(1);
      content = upToIndex(indexOrEnd(char));
      text = text.slice(1);
      return content;
    };
    fragments = [];
    while (text !== '') {
      if (text[0] === '*') {
        content = takeUpTo('*');
        fragments.push({
          content: content,
          type: 'emphasis'
        });
      } else if (text[0] === '{') {
        content = takeUpTo('}');
        fragments.push({
          content: content,
          type: 'footnote'
        });
      } else {
        content = takeNormal();
        fragments.push({
          content: content,
          type: 'normal'
        });
      }
    }
    return fragments;
  };

  show(splitParagraph(p));

}).call(this);
